### ISSUE TITLE
Rename Event Tree to Event Stream

### ISSUE THREAD

**Issue by asomov** [yaml/yaml-spec#266]
The spec in many places uses confusing terminology.
The stream of Events can be represented in many ways, but it should be called by what it is.

**Comment by Thom1729** [comment]
Thanks for the feedback.

One of the goals of the 1.2.2 spec was to be precise and consistent in our use of terminology. The 1.2.1 spec refers at some times to a “serialization tree” and at other times to “serialization events”. These two concepts express the same information, so it makes sense to pick one and use it consistently.

Why go with the tree model rather than a stream of events? Two reasons. First, the serialization tree was already fully defined in the 1.2.1 spec, whereas events were not. This made standardizing on the tree terminology a much smaller and less intrusive change to the spec. Second, the tree model is just easier to define and specify.

To be clear, a serialization tree is exactly isomorphic to a stream of serialization events subject to certain constraints. But those constraints are key. Take the following example of an invalid event stream:

```
+STR 
+DOC
=VAL :Hello, World!
-SEQ
-DOC
-STR
```

Each of the events in the example is correct and valid *in itself*, but the stream of events is structurally invalid. The structural constraints can be succinctly defined as follows: the stream must be the traversal of some serialization tree. Defining those constraints without reference to a tree would be complicated and unintuitive. We could say that the events must match a certain context-free grammar — but this is just sneaking a tree structure in through the back door.

What if we handwave the constraints? For one thing, I think the spec is not the place to handwave if we can avoid it. But also, there is no defined failure point for a malformed event stream, so a malformed event stream could lead to undefined behavior. One might point out that a parser should never produce a malformed event stream — but this is because the language grammar is itself fundamentally a tree structure. It's trees all the way down, and I think we best serve spec readers by making this explicit.

So it's easy to formally define the serialization model as a tree, and then the event stream is just a straightforward traversal of the tree. Having defined the tree model in the spec, we don't need to define an event stream model, as it would be superfluous to the spec.

Having said all this, we are open to improving the spec to make all of this clearer. It seems to me that an easy win would be to add an informative note to the section defining the serialization tree explaining that many implementations use an event stream model internally, that an event stream model can represent the same information as the tree model, and that either can be converted to the other.

P.S. While many implementations use an event stream internally, I'm not sure that these implementations' event streams are completely interoperable. In addition, I believe that some include presentational information (like scalar style) that is not properly part of the serialization model. To be clear, there is nothing wrong with an implementation doing this. I mention it because it means that even if we did define an event stream serialization model in the spec, it might not match existing implementations' event stream models.

**Comment by asomov** [comment]
Agreed. We can name it properly a stream and make a note "_that an event stream model can represent the same information as the tree model,_" as you suggested.

**Comment by asomov** [comment]
@Thom1729 the 2 reasons you mentioned are not enough to justify the wrong terminology. The first one  is not an argument at all - this issue is all about fixing the confusion and wrong terminology. The second is unclear - it is simple for one developer why should it be a part of the spec ?

**Comment by tanriol** [comment]
@asomov Could you please clarify what places of the spec need changes?

Are you talking only about removing the specific "event tree" phrase that's used only in Figure 3.1. "Processing Overview"? Are you talking about adding event stream as a separate concept along with serialization tree? Or is it the serialization tree concept as a whole that, in your opinion, needs to be modified/removed/replaced?

**Comment by asomov** [comment]
Yes, the concept of "serialization tree" is renamed to "serialization stream". [The diagram](https://yaml.org/spec/1.2.2/#31-processes), text.
It is just a rename. The reflect the reality

**Comment by tanriol** [comment]
By reflecting "the reality" do you mean reflecting event-based APIs already used in some specific YAML implementation(s)? What are these implementations? Are they using some shared form of an event stream or are their events / event streams different and incompatible?

AFAIK, neither the "serialization tree" representation nor the "event stream" one are required for a YAML processor, and none of them are actually used in every YAML processor. Yes, these are two different kinds of representations; both are possible. It's not like one of them is "right" and the other one is "wrong". There are parsers that actually can use both of them in different places.

At the moment the 1.2.2 specification mentions events in a few places, including one mention of "an alias event", but does not provide any specifics. If the event stream becomes a part of the specification, it'll likely need a description of possible events and the validity constraints on the event stream. The serialization tree does not require that because it already consists of YAML nodes that are described in the specification (it could use some clarifications, but these are much smaller). Sounds like changing the spec your way would be a significant effort, not "just a rename".

Extra context: some serialization tree vs event stream discussion took place in #42 and the switch to the serialization tree terminology happened in #130.

**Comment by asomov** [comment]
As far as I can see there is no single argument to call it "serialization tree". The only argument which is given - "it is the same".
If it is the same, let us give the better name (to avoid confusion)

**Comment by tanriol** [comment]
Both names can be used wrong and both names can cause confusion. Why do you believe the confusion from "serialization tree" to be greater than from "serialization stream"? Do you want to keep references to the serialization tree in some parts (which?) or to completely drop that term from the specification? How about the [glossary](https://yaml.org/spec/1.2.2/ext/glossary/)?

> ...argument to call it "serialization tree".

Which "it" are you talking about here? Serialization tree and serialization events are separate things, although closely related. It would not be correct to just replace "serialization tree" with "serialization events" in the text because they're *not the same*.

Yes, it would be possible to *rewrite* the corresponding parts of the spec in terms of event stream instead of serialization tree (or to add text describing both and the relationship between them in more detail). However, that would require more effort than just search-and-replace as you seem to imply.

The main argument for the serialization tree model seems to be that it naturally implies a number of constraints that one would need to write down explicitly in the event stream model... and that the constraints on the event stream mostly boil down to "must correspond to a depth-first traversal of some valid serialization tree", so trying to write them down without mentioning the tree would be really unnatural.

The second argument is that the serialization tree consists of the nodes already used in the specification, so it's an easy addition, while serialization events would need to be described separately if they're to be used as a step in YAML processing. That might be less of a problem if you're ready to write the newly required parts of the spec.

**Comment by asomov** [comment]
@tanriol I am sorry - I have nothing to say to you, because it looks like want to turn the discussion to the completely different direction. You asked an explicit question and you received an explicit answer. Why do you ignore it ? Can you please stop discussion about any changes in the spec. I do not propose it. It is just to rename a term to use the correct one. That's it.
Can you please read the title ?

**Comment by perlpunk** [comment]
I understand the point @asomov makes.

### Why I generally agree that the term "Tree" is a good choice.

I think we can all agree that the arrows between Presentation and Serialization [Figure 3.1. Processing Overview](https://yaml.org/spec/1.2.2/#31-processes) stand for a series/sequence of events. That's what needed *during* the parsing process.
What many implementations do, is to pass these events directly to the next stage (composing, or even constructing directly).

Then it can make sense for the next stage to accept a sequence of events as well. First constructing a tree of events from the parse process event sequence. and then traversing the tree over again to get a sequence is not needed.

Still, the hypothetical model that you have between those two stages, the serialization, can be called a tree, and if you would want to save it in between, the most *logical* form (not necessarily the easiest form) would be a tree.

The `test.event` form in the YAML Test Suite, for example, is a very simple text representation of a tree, using `+` and `-`, and optional visual indenting:
```
+STR
 +DOC
  =VAL
 -DOC
-STR
```

Clarifying such things in the spec can of course be helpful, but I don't see a problem with calling the serialization a tree.

### Why "Event Tree" might be confusing

What I agree to is that "Serialization Tree" sounds ok, while "Event Tree" might be confusing.
Events are things that happen during parsing, and once you actually save them into a serialization, then the events have happened in the past.

So "event" is the name that the _arrows_ should be labeled with.

Does that make sense?

**Comment by asomov** [comment]
@perlpunk 

+STR +DOC   =VAL
 -DOC -STR

Here is yet another representation of events. A matrix. Please note that it works exactly the same ways both directions (loading or dumping).
Why we do not call it "representation matrix" ?? It is isomorphic !!!! (same arguments :-)

_To give you the context. I maintain a generic purpose wildly used parser. ANY question, confusion will end up on my shoulders to explain over and over again. 
Can you please do me a favor and save my time and energy for something more useful ?_

**Comment by perlpunk** [comment]
@asomov I'm trying to understand your issue and thought I got it at least partially, but it appears I didn't.

I have yet to see a more complete example of an event matrix, with information of the x and y axes, to see
a) why it would make sense to use this model as an alternative
b) why the spec should use this model

> _I maintain a generic purpose wildly used parser. ANY question, confusion will end up on my shoulders to explain over and over again._

Ok, but I don't see where people would approach you with questions regarding this.
If this has happened, it might be good to cite an example.

I wrote my own YAML lib, but the event API is not yet stable and documented.
However, I have helped maintaining [libyaml](https://github.com/yaml/libyaml) and [pyyaml](https://github.com/yaml/pyyaml), and I think I have read a good portion of their Github issues, and I never saw any question/confusion about the spec calling the serialization a tree.

I really would like to understand the issue, and why it can't be solved by the suggestions that have been made so far. For example, I *did* agree that "Event Tree" can be confusing, and that's what the title of this issue is about ;-)

> _Can you please do me a favor and save my time and energy for something more useful ?_

Several people are investing their time to discuss your issue here.

**Comment by asomov** [comment]
@perlpunk###  short answer: it is a very minor change. It is about fixing a typo. That is why it should be done for the current spec.

**Very long answer.** 
I will try to explain it.

**SARCASM ON**
We should use a "serialization matrix" or even better "serialization zigzag". Because they are isomorphic. They are both just representations of the event stream and I find them better than the chosen "representation tree". The representation with indentation which looks like a tree does not make the events a tree.
**SARCASM OFF**

We can represent the same amount as "V" and as "5". It does not change the amount. In one context "V' may be more appropriate in some context "5".
In the parsers that you mentioned (as in many other if not all) the events form a stream or sequence. Why we should call it anything else ? 

Important: please do not make the issuer bigger !!! Please do not add unrelated stuff (like "Event Tree") - it is a mickey mouse change.

**Comment by asomov** [comment]
I have added explanation [to the docs]
(https://bitbucket.org/snakeyaml/snakeyaml-engine/src/master/CONTRIBUTE.md)
