### ISSUE TITLE
Allow using tabs for indentation in block mode

### ISSUE THREAD

**Issue by ExE-Boss** [yaml/yaml-spec#40]
[Tabs are the superior choice](http://nickgravgaard.com/elastic-tabstops/), and I absolutely hate using spaces for indentation.

Also, with spaces, it’s easy to miss a space in long lines, whereas tabs are a lot wider, which makes it easier to tell indentation at a glance.

All you need to do is disallow mixing spaces and tabs, just like how Python does it.

---

Seriously, if I had designed YAML, then I would’ve required using tabs for indentation, because spaces take up 4 times as many bytes as tabs, and that’s terrible.

**Comment by ioquatix** [comment]
I've seen this discussed quite a bit, especially relating to YAML. I would really love to see this implemented.

**Comment by craigbarnes** [comment]
>One of the most convincing arguments for supporting tabs: https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/

I don't find that a very compelling argument. Many people use git's `autocrlf` feature, so that Windows users can edit their files with CRLF linebreaks but have them automatically converted to LF in the repo. You can do something similar for indentation with git clean/smudge filters. In fact, there are people already doing this now, without other users of the repo even knowing about it.

https://stackoverflow.com/questions/2316677/can-git-automatically-switch-between-spaces-and-tabs

The advantages of spaces is that their rendering is always unambiguous in every context. The same can't be said for tabs and their flexibility isn't always a good thing.

**Comment by ingydotnet** [comment]
There are plans to discuss tab indentation in the upcoming versions of YAML. These ideas should become public in the next few weeks. I won't detail them here, but they are just plans to discuss tab indentation, not necessarily accept it.

**Comment by ioquatix** [comment]
Thanks for the update.

In the context of git, your proposed solution may be useful. However this doesn't just apply to YAML stored in git repositories.

> I don't find that a very compelling argument.

Lots of people find the accessibility argument compelling because it allows people who would otherwise struggle with visual impairments to read the code.

Do you have any arguments for *not* supporting tabs for indentation in YAML?

I look forward to the updated proposal. Can you link through when the plans are made available? Thanks :)

**Comment by craigbarnes** [comment]
> Do you have any arguments for not supporting tabs for indentation in YAML?

* It avoids having to specify behaviour for mixed indents
* Tabs have any number of interpretations (4 columns, 8 columns, terminal tab stops, "elastic tab stops" as linked [above](https://github.com/yaml/yaml-spec/issues/40#issue-489983562)), whereas a space is always just a space
* etc.

**Comment by ioquatix** [comment]
> It avoids having to specify behaviour for mixed indents.

That's a reasonable point, but it's also not a hard one to specify if it's needed. Just define them as completely independent.

> Tabs have any number of interpretations (4 columns, 8 columns, terminal tab stops, "elastic tab stops" as linked above), whereas a space is always just a space.

A tab is a semantic unit of indentation. In YAML you could treat it as one space for the purpose of computing indentation.

https://yaml.org/spec/1.2/2009-07-21/spec.html#id2576668

As outlined on the above specification, a space is never "just a space". You have spaces which are treated as indentation, spaces which are considered alignment, spaces which are merged together for the purpose of computing indentation, spaces which are ignored, etc. Having written code that deals with this kind of parsing, I can tell you it's non-trivial, and yes it gets tricky if you assume users are going to use both tabs and spaces interchangeably, since by definition a tab has no equivalent fixed number of spaces.

> etc.

???

**Comment by craigbarnes** [comment]
>As outlined on the above specification, a space is never "just a space". You have spaces which are treated as indentation, spaces which are considered alignment

I wasn't talking about language semantics, I was talking about editing/rendering. Text formats don't exist in a vacuum; editing considerations are just as important as parsing considerations.

A space is exactly 1 column in a terminal (or a specific width in a proportional font). If you only allow spaces, then whitespace looks the same in any editor, which makes it much harder to mess up indents because of rendering differences. The same most definitely can't be said if you allow tabs. People *will* mix them and no 2 people can agree on how a tab should look in an editor. Not allowing tabs just avoids all that.

People argue in favor of tabs because they're "flexible", but that's the thing that causes all the problems.

**Comment by ioquatix** [comment]
> which makes it much harder to mess up indents because of rendering differences.

This is very subjective. I've seen plenty of code with messed up indentation because people insert extra single spaces, e.g. a file which is predominately 2-space indentation suddenly has a 3-space indentation. Such class of errors is not possible with tabs unless you completely misindent a block.

Looking at the YAML specification, this almost seems encouraged - there is no notion of "indentation level" but more "indent more or less than the previous level" to change indentation.

**Comment by ioquatix** [comment]
I created an RFC for supporting tab indentation, but it was closed. https://github.com/yaml/yaml-spec/pull/109

**Comment by minecraftchest1** [comment]
I just spent 5 minutes why a program that reads a YAML file blew up because I used a tab instead of a space. This is RIDICULOUS! In my opinion, anyone requiring spaces for code indentation is someone who is not worth my time talking to. And I totally agree with the accessibility argument. Also, by indenting with a tab, I don't have to spend 5 minutes trying to figure out how many spaces an indent is. Seriously people.

**Comment by nyuszika7h** [comment]
it's unfortunate that the yaml spec writers decided to disallow tabs due to misguided notions. tabs could be used perfectly fine in yaml if you use them as intended: tabs for indentation, spaces for alignment. (in the example below, `➢───` signifies a tab character)

```yaml
items:
➢───- apple
➢───  pear
➢───  orange
```

**Comment by kripper** [comment]
Is there any yaml fork for python that supports tabs?

**Comment by ed2050** [comment]
> Is there any yaml fork for python that supports tabs?

There is now.  Thanks kripper!  copying your post from other thread so people here find it:

> I forked PyYAML and added tabs indentation support here:
> https://github.com/kripper/pyyaml

**Comment by kripper** [comment]
Thanks. Tabs are unfairly underrated. Why use 2 or 4 spaces when you can have a single tab character, right?
