### ISSUE TITLE
Discussion of RFC-003 -- Characters allowed in anchor names

### ISSUE THREAD

**Issue by ingydotnet** [yaml/yaml-spec#46]
Use this issue to comment on [RFC-003 -- Characters allowed in anchor names](https://github.com/yaml/yaml-spec/blob/master/rfc/RFC-003.md).

**Comment by FichteFoll** [comment]
I suggest linking the document in the original post. Here it is for convenience: https://github.com/yaml/yaml-spec/wiki/RFC-003

**Comment by ingydotnet** [comment]
@FichteFoll that's a good idea. Thanks. I'll do that for the remaining RFC-s which I am working on currently. I just updated the intro comment for this issue.

Note that the new canonical URL for is https://github.com/yaml/yaml-spec/blob/rfc/RFC-003.md. You may wish to delete the wiki URL in your comment above.

See #47 for a bit more detail.

**Comment by peterkmurphy** [comment]
At the moment, the YAML 1.2 spec allows the following [EBNF for anchors and alias names](https://yaml.org/spec/1.2/spec.html#id2785586):

```
[102] ns-anchor-char ::= ns-char - c-flow-indicator 
[103] ns-anchor-name ::= ns-anchor-char+
```
This is where the problem lies. Except for five exceptions: “[”, “]”, “{”, “}” and “,”, any non-space character is allowed in anchor names, even characters like “*” and “&”. This makes it really hard to write a parser that accommodates these cases.

For my mind, the simplest solution is to alter production [102] so that more characters are excluded.  Something like this would work for me:
```
[102] ns-anchor-char ::= ns-char - c-flow-indicator - “?” - “:” - “#” - “&” - “*” - “!” - “|” - “>” - “'” - “"” - “%” - “@” - “`” - #x85 -#x2028 - #x2029
```

There's an argument about which characters should and shouldn't be added, but at least [102] doesn't exclude forward slashes, underscores, hyphens and dots, or Unicode alphanumeric characters in general. It is also not hard to modify existing code to accommodate this sort of thing (I've done it in both Python and C). Code point ranges are large and continuous (quick and easy to parse)

With EBNF like this, in contrast, you get a lot of discontinuous pieces:

```
\p{Letter} | \p{Number} | '_' | '-' | '.' | '/'
``` 
Another reason I feel uncomfortable about this statement is that it really depends on which library you are using to look up the Unicode Character Database (UCD), which defines character properties for all Unicode characters. Python has a unicodedata module which does this. Unfortunately, while the latest version of the UCD is 13, Python 3.8.2's unicodedata module only refers to 12.1.0, unicodedata for 3.7.7 only refers to 11.0.0, 3.6.10 refers to 9.0.0, 3.5.9 refers to 8.0.0, and (yes, for completeness), 2.7.18 refers to version 5.2.0 of the Unicode database. 

My point is that with even small differences in language and library, there will be different results for evaluating \p{Letter}, all of which _will be almost invariably out of date_. Let's not put YAML parser writers in this position. Don't force them to either write their own unicode character database library, or rely on third party efforts. Let's modify EBNF statement [102] and leave it at that.

**Comment by perlpunk** [comment]
I basically agree with @peterkmurphy . Interoperability is one of YAML's weaknesses, because many implementations are different. One reason is that there was no testsuite from the beginning.

Adding additional things that libraries MAY implement, and in this case highly depend on the unicode support, are bad for interoperability.

**Comment by peterkmurphy** [comment]
Thinking a bit more about it, my [102] EBNF statement allows "<" but forbids ">", which would seem odd. It also allows a few characters like "+" and "~", which are probably not necessary. So I would rewrite the statement as:
```
[102a] ns-anchor-forbid ::= [#x21-#x2C] /* !,", #, $, %, &, ', (, ), *, +, and comma */
| [#x3A-#x40] /* :, ; <, =, >, ? and @ */
| [#x5B-#x5E] /* [, \, ],  and ^ */
| #x60 /* ` */ 
| [#x7B-x7E] /* {, |, }, and ~ */
| #x85 
| [#x2028-#2029]
[102b] ns-anchor-char ::= ns-char - ns-anchor-forbid 
```

**Comment by ingydotnet** [comment]
I don't think that anchors prevent interoperability much if at all. Programs emit very simple anchors that  like `&1`, `&001`, `&id1` etc. So program to program interop is not an issue. Humans using fancy names are usually working within a domain specific system, so interoperability is not normally an issue.

Currently libyaml supports `-_A-Za-z9-9` and that's the basis of a large number of YAML frameworks. WDLYD (what does libyaml do) will always weigh in heavily. The author (wisely imho) broke with the spec in a few places where it didn't make sense.

The plan here is to:
* Remove the syntax chars from anchor names. That's an obvious mistake.
* Keep the mandatory set simple for now. The fact that libyaml is restricted makes me comfortable in this.
* Allow the frameworks that have allowed the larger unicode set to work, to continue working.
* Move towards that set in a later release.

Let me point out a few things that I'm sure I'll be repeating. Changing YAML is going to be hard and some nuanced decisions need to be made. Sometimes we will need to risk breaking a few eggs to make this meal. This is one of those areas where as far as I can see in the real world, simplifying the set is not going to cause many problems. I am certainly willing to listen to all arguments, but I'll be moved more by real life situations.

**Comment by peterkmurphy** [comment]
I'm a little concerned here. Is this leading up to RFC-003 (and by extension libyaml and pyyaml) disallowing Unicode characters in anchor and alias names? This seems a very, very bad idea if that is the case. 

(I should add that my concern here is **not** whether RFC-003 is going to allow or forbid YAML syntax characters like ampersands and asterisks. My view is that they should have never been allowed in the first place, and tightening up the specification here is fully warranted.)

**Comment by perlpunk** [comment]
> I don't think that anchors prevent interoperability much if at all. Programs emit very simple anchors that like `&1`, `&001`, `&id1` etc. So program to program interop is not an issue. Humans using fancy names are usually working within a domain specific system, so interoperability is not normally an issue.

I don't think that interop is restricted to program to program interaction.

Library A supports fancy anchor names.
Application B is using Library A.
Library C does only support `a-zA-Z0-9_-`.
People want to use an application D (using Library C) to do something with the files for Application B.
A very simple and common example is yamllint. No matter in what language and for what library you write your YAML files, yamllint is a common choice for checking formatting and basic syntax.

There can be other use cases where you want to read YAML files written for one application with another application.

Currently at my work there is a team that has already the problem that they can't use yamllint because they are using a YAML library that allows invalid YAML, and they were not aware that it's invalid.

You might have never had that use case, but I think it's not fair to say that ino use case exists because of that.

I think it is one of YAML's weaknesses, and it would be sad for me to see that the future of YAML is going into that direction of non-interop on purpose.

When I'm talking about YAML (to my colleagues, or in conference talks), I usually say that different YAML libraries behave differently, but that we're working on fixing it (with the test suite, and trying to fix existing libraries).
I haven't been really talking about YAML 1.3, and I would be ashamed to tell people that the new spec would make things optional for basic syntax elements, because that would contradict my previous statement.

Of course I know that also lot of YAML is not just basic configuration data, and contains domain specific things (like AWS and their `!Join` and `!Ref` tags). Of course you can't read such files with a basic YAML library (or at least the tags woul be ignored).
But the use case to read such files with other programs exist, and it's not that hard to implement it. A Perl module exists to read and write AWS Cfn files with such tags, although AWS itself is not using Perl for that. I'm sure the author didn't just implement this for fun. They have a use case.

So yes, I can see that many YAML files might contain more than just simple configs, and you can't possibly throw any YAML lib at any YAML file.

**But** it would be really great if we as YAML library authors could at least rely on the basic syntax elements like anchors being the same everywhere.

**Comment by peterkmurphy** [comment]
Well said, @perlpunk.

**Comment by ingydotnet** [comment]
Locked until we flesh out and document the RFC process more.

**Comment by ingydotnet** [comment]
https://github.com/yaml/yaml-spec/wiki/YAML-RFC-Process

Closing this until we formalize the process
