### ISSUE TITLE
Discuss: RFC-0002 - Documents after the first require a document-start-indicator

### ISSUE THREAD

**Issue by ingydotnet** [yaml/yaml-spec#73]
RFC: https://github.com/yaml/yaml-spec/tree/master/rfc/RFC-0002.md

See: https://github.com/yaml/yaml-spec/tree/master/rfc/ReadMe.md

**Comment by ssbarnea** [comment]
@perlpunk It would really be nice if we could get some official and clear guidelines, ones that document a canonical format to follow, at least for those that want to be strict. I used to assume that ideally `---` should be at start of any document, but received multiple complaints regarding "why? what is the benefit?". I may be biased as while I use YAML a lot, it is always for configuration files/management and I never encountered a real need to use multi-documents per-file.

Especially for linters and formatters it is essential to get help from the spec team in order to define clear behaviors. This is important because a predictable formatting avoids divergence and endless discussions during code reviews: `john: you forgot the ---! alan: why you added the ---? ...`

Please note that I am not proposing making one option or another a syntax error, but I am proposing documenting a canonical/normalized format. A good example of similar issue was the canonical format with Unicode, one that aimed to fix issues where the same text could be written in multiple forms, causing serious platform compatibility bugs. They introduced a normalized forms for that. Lucky for yaml is should be much easier to do something like that.

Basically this is about avoiding undetermined desired behavior when using "optional". If document-start is optional at the beginning of the file, we should also mention the desirable normalized form with or without it.

I am personally inclined to support avoiding it at start of file when not needed, mainly due to KISS.

**Comment by perlpunk** [comment]
@ssbarnea I agree that guidelines for things like that are helpful :) 

But most of the RFCs (is this one) target the specification, saying if something is valid or not, not if it's recommended or not.
This RFC is about multi document streams, where all documents *after* the first require a header.
e.g. currently it is allowed to seperate documents with the document footer:
```
a: b
...
c: d
```

The discussion of guidelines should be moved into its own issue. I can provide some input on that, but not in this issue here.

**Comment by ssbarnea** [comment]
@perlpunk I removed my comment and created https://github.com/yaml/yaml-spec/issues/77 feel free to comment or even edit its description.

**Comment by ingydotnet** [comment]
Locked until we flesh out and document the RFC process more.

**Comment by ingydotnet** [comment]
See: https://github.com/yaml/yaml-spec/wiki/YAML-RFC-Process

Closing this until we formalize the RFC process.
