### ISSUE TITLE
Discuss: RFC-0004 - Maximum of 8 spaces per indentation level

### ISSUE THREAD

**Issue by ingydotnet** [yaml/yaml-spec#76]

**Comment by champignoom** [comment]
Against.

YAML should chop off surprises instead of (re-)introducing any. Random opinions like whether >8 spaces are/could be too much should be kept from a serious specification. The two reasons mentioned in the RFC don't really hold anyway: 1) indentation is nothing special in terms of breaking parsers with an amount of petabytes 2) similarly, indentation is no different from any spaces for casual observations, and whatever a long indentation could hack, the same thing could be achieved by a long trailing sequence of spaces followed by a one-liner object.

**Comment by ingydotnet** [comment]
@champignoom Greetings. It seems you came across our RFC process while it's still being set up. We're still sorting out how this process works, how future releases are specced and the public involvement of it. I expect we'll have most of the information for public participation ready in the next 6 weeks. In the meantime the repo has been temporarily restricted to the core team.

wrt to your comment, I agree with you at least that this RFC's reasoning is a little weak and we'll take a took at adjusting it. Thanks.

**Comment by ingydotnet** [comment]
Locked until we flesh out and document the RFC process more.

**Comment by ingydotnet** [comment]
See: https://github.com/yaml/yaml-spec/wiki/YAML-RFC-Process

Closing this until we formalize the RFC process.
