### ISSUE TITLE
Broken link to RFC-0008

### ISSUE THREAD

**Issue by prescod** [yaml/yaml-spec#78]
This wiki page:

https://github.com/yaml/yaml-spec/wiki/RFC-008

Refers to this missing page:

https://github.com/yaml/yaml-spec/blob/rfc/RFC-008.md

This issue is of interest to me because I'm the creator of a Jinja-embedding language.

https://snowfakery.readthedocs.io/en/docs/

Hi Ingy!

**Comment by simcop2387** [comment]
This looks to be the case for every single link like this on all RFCs

**Comment by ingydotnet** [comment]
The RFCs are a bit of a mess., but we are in the process of sorting it out...

The RFCs started out in a wiki in 2017 here: https://github.com/yaml/summit.yaml.io/wiki
During a week in Berlin with @ingydotnet @perlpunk and @flyx.

In 2018 they were moved here: https://github.com/yaml/yaml-spec/wiki

Then in 2020 @ingydotnet @perlpunk @pantoniou and @eemeli retired those RFCs making a full internal list of those and more, to be published as permanent RCFs in this repo. We have been in weekly planning meetings since Spring 2020.

The effort stalled out a bit but will resume shortly after we finish the YAML spec 1.2.1 patch publication (for YAML 1.2) which should hit the wire in the next 60 days.

Hi Paul!

It's been a minute or two... (Paul was my coworker at ActiveState when YAML was being born (2001)).
I had no idea you made Jinja. That's so rad!

We've figure out quite a bit since RFC-008. Plans are forming that will make templating natural in pure YAML, but would also make benefit Jinja use in YAML. I'd love to brainstorm on it with you.

I'll reach out to you soon...

**Comment by prescod** [comment]
Hello INGY!

No, I don't make Jinja. I make a language that embeds Jinja into Yaml.

https://medium.com/salesforce-architects/generate-realistic-datasets-with-snowfakery-5349225b033d

https://snowfakery.readthedocs.io/en/stable/#formulas

Still would love to brainstorm with you (and just catch up!) but I can't speak as a Jinja-developer, but rather as a Jinja-user.

**Comment by ingydotnet** [comment]
> No, I don't make Jinja. I make a language that embeds Jinja into Yaml.

Good enough!

> Still would love to brainstorm with you (and just catch up!) ...

YES!

**Comment by ingydotnet** [comment]
See: https://github.com/yaml/yaml-spec/wiki/YAML-RFC-Process

Closing this until we formalize the RFC process.
